apiVersion: v1
kind: Service
metadata:
  name: mitmproxy
spec:
  selector:
    app: mitmproxy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: proxy
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: web
